# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import generics.mixin.modelmixin.filter_model_mixin
import generics.mixin.modelmixin.permission_model_mixin
import generics.mixin.modelmixin.searchable_model_mixin
import generics.mixin.modelmixin.template_provider_mixin


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('date_created', models.BigIntegerField()),
                ('last_updated', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generics.LocationEntity')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, generics.mixin.modelmixin.permission_model_mixin.PermissionModelMixin, generics.mixin.modelmixin.filter_model_mixin.FilterModelMixin, generics.mixin.modelmixin.template_provider_mixin.TemplateProviderMixin, generics.mixin.modelmixin.searchable_model_mixin.SearchableModelMixin),
        ),
    ]
