from enum import Enum


class PROMOTION_REWARD_TYPES(Enum):
    AMOUNT_IN_MONEY = 0
    FREE_SHIPPING = 1
    FREE_PRODUCTS = 2
    ACCESSORIES = 3
    STORE_CREDIT = 4


class DISCOUNT_REWARD_TYPE(Enum):
    AMOUNT_IN_MONEY = 0
    FREE_SHIPPING = 1
    FREE_PRODUCTS = 2
    ACCESSORIES = 3
    STORE_CREDIT = 4


class PROMOTION_TYPES(Enum):
    BUY = 0
    RENT = 1

class TRANSACTION_TYPES(Enum):
    CREDIT_STORE = 0
    BUY = 1
    RENT = 2
    SALE = 3