# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bauth', '0001_initial'),
        ('book', '0002_auto_20161126_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bauth.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bauth.Country'),
            preserve_default=False,
        ),
    ]
