# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='short_name',
            new_name='short_name2',
        ),
        migrations.AddField(
            model_name='country',
            name='short_name3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
