# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0002_locationentity'),
        ('book', '0003_auto_20161205_1751'),
        ('bauth', '0002_auto_20161205_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='country',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='district',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='district',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='district',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='state',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='state',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='state',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='upazila',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='upazila',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='upazila',
            name='parent',
        ),
        migrations.AlterField(
            model_name='adress',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bauth.Country'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bauth.District'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bauth.State'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='upazila',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bauth.Upazila'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Upazila',
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('generics.locationentity',),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('generics.locationentity',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('generics.locationentity',),
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('generics.locationentity',),
        ),
    ]
